# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# Some additional sample template:
# https://devhub.io/repos/goreleaser-goreleaser
# https://dev.to/mstrsobserver/painless-github-releases-with-drone-and-goreleaser-45b7
#
# git tag -a v0.1.0 -m "First release"
# git push origin v0.1.0
#
# goreleaser --snapshot --skip-publish --rm-dist
#
project_name: netio

env:
  - GO111MODULE=on

before:
  hooks:
    - cmd /c git --no-pager log --pretty=format:"%h%x09%x09%ai%x09%s" -- 1> CHANGES.txt
    - go mod tidy

builds:
  - binary: netio
    id: netio
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

archives:
  - id: netio
    format: zip
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - LICENSE
      - CHANGES.txt
      - README.md
    #    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: macos
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
#https://goreleaser.com/artifactory/
#
#artifactories:
#  - name: production
#    target: http://<Your-Instance>:8081/artifactory/example-repo-local/{{ .ProjectName }}/{{ .Version }}/
#    username: goreleaser

release:
  draft: false

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
